version: '3.8'

services:
  postgres:
    image: postgres:16.0
    container_name: postgres_container
    environment:
      POSTGRES_USER: "alonmell"
      POSTGRES_PASSWORD: "qwerty"
      POSTGRES_DB: "ProviderHub"
    ports:
      - "5432:5432"